package com.yellowbrossproductions.illageandspillage.util;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class IllageAndSpillageSoundEvents {
    public static final DeferredRegister<SoundEvent> SOUND_EVENTS;
    public static final RegistryObject<SoundEvent> ENTITY_IGNITER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_IGNITER_CELEBRATE;
    public static final RegistryObject<SoundEvent> ENTITY_IGNITER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_IGNITER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_THROW;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_REPAIR;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_HINDER_HEAL;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_BEEPER_BEEP;
    public static final RegistryObject<SoundEvent> ENTITY_ENGINEER_POKER_POKE;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_INTRO;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_MUSIC;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_CELEBRATE;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_PREPARE_FAKERS;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_SPIN;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_ARROWBARRAGE;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_HEAL;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_DISPENSER;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_DISPENSER_OPEN;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_DISPENSER_DESTROY;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_FANGRUN;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_SUMMON;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_CAST_SPELL;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_FIREBALL;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_LIFESTEAL;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_RAVAGER;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_RAVAGER_ROAR;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_FORCEFIELD;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_FIREBALL_START;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_SWING_BAT;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_LIFESTEAL_START;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_FANGRUN_START;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_POTIONS;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_POTIONS_START;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_CROSSBOWSPIN;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_LOAD;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_SHOOT;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_HEAL_INTERRUPT;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_KABOOMER_EXPLODE;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_KABOOMER_HISS;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_KABOOMER;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_LAUGH;
    public static final RegistryObject<SoundEvent> ENTITY_MAGISPELLER_ESCAPE;
    public static final RegistryObject<SoundEvent> ENTITY_FAKER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_FAKER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_CELEBRATE;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_SCREAM;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_EXPLODE;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_DING;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_HMM;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_ANGRY;
    public static final RegistryObject<SoundEvent> ENTITY_TWITTOLLAGER_CHARGE;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_WINGS;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_CELEBRATE;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_INTRO;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_MUSIC;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_MUSIC_APRIL;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_STEALSPIRITS;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_SPIRITABSORB;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_SPIRITSWARM;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_SOULSCREAM;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_BLOCKALERT;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_EARTHRUMBLE;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_IMPLAUGH;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_DEATHANIMATION;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_DESCENT;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_IMPRISE;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_CLAP;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_SPIRITHANDS;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_SPIRITHAND_WARN;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_CHARGELASER;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_LASER;
    public static final RegistryObject<SoundEvent> ENTITY_SPIRITCALLER_ANTICHEESE;
    public static final RegistryObject<SoundEvent> ENTITY_MOBSPIRIT_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_MOBSPIRIT_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_MOBSPIRIT_HURTCORRUPTED;
    public static final RegistryObject<SoundEvent> ENTITY_MOBSPIRIT_DEATHCORRUPTED;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_BOSS;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_FINALBOSS;
    public static final RegistryObject<SoundEvent> ENTITY_BOSSRANDOMIZER_GOOFY;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_BITE;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_PREPARE_CHARGE;
    public static final RegistryObject<SoundEvent> ENTITY_CROCOFANG_CHARGE;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_RAVAGERMUTATE;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_INTROEXPLOSION;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_SLAMGROUNDINTRO;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_INTROROAR;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_DEATHGROUND;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_PREPARE_WALLCRASH;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_WALLCRASH;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_STEP;
    public static final RegistryObject<SoundEvent> ENTITY_DEVASTATOR_LAND;
    public static final RegistryObject<SoundEvent> ENTITY_ABSORBER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_ABSORBER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_ABSORBER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_ABSORBER_ATTACK;
    public static final RegistryObject<SoundEvent> ENTITY_ABSORBER_COLLAPSE;
    public static final RegistryObject<SoundEvent> ENTITY_PRESERVER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_PRESERVER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_PRESERVER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_PRESERVER_JUMP;
    public static final RegistryObject<SoundEvent> ENTITY_PRESERVER_LAND;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_REVEAL;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SKID;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_VILLAGERWAVE;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_VILLAGERSIGH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_FORCEPOTION;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_AXE_DRAW;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_THROW;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_PUMPKINBOMBS;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_MINIONS;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_ANGRYAXES;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_LAUGH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_MUSIC;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_VILLAGERPANIC;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SHIVER;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_CYMBAL;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SKULLBOMB_EXPLODE;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_PUMPKINBOMB_EXPLODE;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_VILLAGERHISS;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_PUMPKINBOMB_BOING;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SPIN;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SCYTHE_SPIN;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_SCYTHE_CATCH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_TRICKORTREAT_DESTROY;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_TRICKORTREAT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_TRICKORTREAT_BOUNCE;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_FUNNYBONE_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_FUNNYBONE_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_FUNNYBONE_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_FUNNYBONE_THROW;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_EYESORE_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_EYESORE_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_EYESORE_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_FREAKAGER_EYESORE_LAND;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_TRANS;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_MUSIC;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_AMBIENT;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_HURT;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_DEATH;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_CRAWL;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_BLOCK;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_PREPARECHARGE;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_LEAP;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_ROAR;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_WEB;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_SPAWN;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_SCREECH;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_JUMPSCARE;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_EAT;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_SLAM;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_WEB_HIT;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_CHARGE;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_COUGH;
    public static final RegistryObject<SoundEvent> ENTITY_RAGNO_STUN;
    public static final RegistryObject<SoundEvent> TOTEM_BANISHMENT;
    public static final RegistryObject<SoundEvent> SPELLBOUND_BOOK_USE;
    public static final RegistryObject<SoundEvent> MAGI_DISC;
    public static final RegistryObject<SoundEvent> SPIRI_DISC;
    public static final RegistryObject<SoundEvent> FREAKY_DISC;
    public static final RegistryObject<SoundEvent> GHOST_BLOCK_REPAIR;

    public IllageAndSpillageSoundEvents() {
    }

    private static RegistryObject<SoundEvent> addSoundsToRegistry(String soundId) {
        ResourceLocation id = new ResourceLocation("illageandspillage", soundId);
        return SOUND_EVENTS.register(soundId, () -> SoundEvent.createVariableRangeEvent(id));
    }

    static {
        SOUND_EVENTS = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, "illageandspillage");
        ENTITY_IGNITER_AMBIENT = addSoundsToRegistry("entity.igniter.ambient");
        ENTITY_IGNITER_CELEBRATE = addSoundsToRegistry("entity.igniter.celebrate");
        ENTITY_IGNITER_HURT = addSoundsToRegistry("entity.igniter.hurt");
        ENTITY_IGNITER_DEATH = addSoundsToRegistry("entity.igniter.death");
        ENTITY_ENGINEER_AMBIENT = addSoundsToRegistry("entity.engineer.ambient");
        ENTITY_ENGINEER_HURT = addSoundsToRegistry("entity.engineer.hurt");
        ENTITY_ENGINEER_DEATH = addSoundsToRegistry("entity.engineer.death");
        ENTITY_ENGINEER_THROW = addSoundsToRegistry("entity.engineer.throw");
        ENTITY_ENGINEER_REPAIR = addSoundsToRegistry("entity.engineer.repair");
        ENTITY_ENGINEER_HINDER_HEAL = addSoundsToRegistry("entity.engineer.hinder.heal");
        ENTITY_ENGINEER_BEEPER_BEEP = addSoundsToRegistry("entity.engineer.beeper.beep");
        ENTITY_ENGINEER_POKER_POKE = addSoundsToRegistry("entity.engineer.poker.poke");
        ENTITY_MAGISPELLER_INTRO = addSoundsToRegistry("entity.magispeller.intro");
        ENTITY_MAGISPELLER_MUSIC = addSoundsToRegistry("entity.magispeller.music");
        ENTITY_MAGISPELLER_AMBIENT = addSoundsToRegistry("entity.magispeller.ambient");
        ENTITY_MAGISPELLER_CELEBRATE = addSoundsToRegistry("entity.magispeller.celebrate");
        ENTITY_MAGISPELLER_HURT = addSoundsToRegistry("entity.magispeller.hurt");
        ENTITY_MAGISPELLER_DEATH = addSoundsToRegistry("entity.magispeller.death");
        ENTITY_MAGISPELLER_PREPARE_FAKERS = addSoundsToRegistry("entity.magispeller.prepare_fakers");
        ENTITY_MAGISPELLER_SPIN = addSoundsToRegistry("entity.magispeller.spin");
        ENTITY_MAGISPELLER_ARROWBARRAGE = addSoundsToRegistry("entity.magispeller.arrowbarrage");
        ENTITY_MAGISPELLER_HEAL = addSoundsToRegistry("entity.magispeller.heal");
        ENTITY_MAGISPELLER_DISPENSER = addSoundsToRegistry("entity.magispeller.dispenser");
        ENTITY_MAGISPELLER_DISPENSER_OPEN = addSoundsToRegistry("entity.magispeller.dispenser_open");
        ENTITY_MAGISPELLER_DISPENSER_DESTROY = addSoundsToRegistry("entity.magispeller.dispenser_destroy");
        ENTITY_MAGISPELLER_FANGRUN = addSoundsToRegistry("entity.magispeller.fangrun");
        ENTITY_MAGISPELLER_SUMMON = addSoundsToRegistry("entity.magispeller.summon");
        ENTITY_MAGISPELLER_CAST_SPELL = addSoundsToRegistry("entity.magispeller.cast_spell");
        ENTITY_MAGISPELLER_FIREBALL = addSoundsToRegistry("entity.magispeller.fireball");
        ENTITY_MAGISPELLER_LIFESTEAL = addSoundsToRegistry("entity.magispeller.life_steal");
        ENTITY_MAGISPELLER_RAVAGER = addSoundsToRegistry("entity.magispeller.ravager");
        ENTITY_MAGISPELLER_RAVAGER_ROAR = addSoundsToRegistry("entity.magispeller.ravager_roar");
        ENTITY_MAGISPELLER_FORCEFIELD = addSoundsToRegistry("entity.magispeller.forcefield");
        ENTITY_MAGISPELLER_FIREBALL_START = addSoundsToRegistry("entity.magispeller.fireball_start");
        ENTITY_MAGISPELLER_SWING_BAT = addSoundsToRegistry("entity.magispeller.swing_bat");
        ENTITY_MAGISPELLER_LIFESTEAL_START = addSoundsToRegistry("entity.magispeller.lifesteal_start");
        ENTITY_MAGISPELLER_FANGRUN_START = addSoundsToRegistry("entity.magispeller.fangrun_start");
        ENTITY_MAGISPELLER_POTIONS = addSoundsToRegistry("entity.magispeller.potions");
        ENTITY_MAGISPELLER_POTIONS_START = addSoundsToRegistry("entity.magispeller.potions_start");
        ENTITY_MAGISPELLER_CROSSBOWSPIN = addSoundsToRegistry("entity.magispeller.crossbowspin");
        ENTITY_MAGISPELLER_LOAD = addSoundsToRegistry("entity.magispeller.load");
        ENTITY_MAGISPELLER_SHOOT = addSoundsToRegistry("entity.magispeller.shoot");
        ENTITY_MAGISPELLER_HEAL_INTERRUPT = addSoundsToRegistry("entity.magispeller.heal_interrupt");
        ENTITY_MAGISPELLER_KABOOMER_EXPLODE = addSoundsToRegistry("entity.magispeller.kaboomer_explode");
        ENTITY_MAGISPELLER_KABOOMER_HISS = addSoundsToRegistry("entity.magispeller.kaboomer_hiss");
        ENTITY_MAGISPELLER_KABOOMER = addSoundsToRegistry("entity.magispeller.kaboomer");
        ENTITY_MAGISPELLER_LAUGH = addSoundsToRegistry("entity.magispeller.laugh");
        ENTITY_MAGISPELLER_ESCAPE = addSoundsToRegistry("entity.magispeller.escape");
        ENTITY_FAKER_AMBIENT = addSoundsToRegistry("entity.faker.ambient");
        ENTITY_FAKER_DEATH = addSoundsToRegistry("entity.faker.death");
        ENTITY_TWITTOLLAGER_AMBIENT = addSoundsToRegistry("entity.twittollager.ambient");
        ENTITY_TWITTOLLAGER_CELEBRATE = addSoundsToRegistry("entity.twittollager.celebrate");
        ENTITY_TWITTOLLAGER_HURT = addSoundsToRegistry("entity.twittollager.hurt");
        ENTITY_TWITTOLLAGER_DEATH = addSoundsToRegistry("entity.twittollager.death");
        ENTITY_TWITTOLLAGER_SCREAM = addSoundsToRegistry("entity.twittollager.scream");
        ENTITY_TWITTOLLAGER_EXPLODE = addSoundsToRegistry("entity.twittollager.explode");
        ENTITY_TWITTOLLAGER_DING = addSoundsToRegistry("entity.twittollager.ding");
        ENTITY_TWITTOLLAGER_HMM = addSoundsToRegistry("entity.twittollager.hmm");
        ENTITY_TWITTOLLAGER_ANGRY = addSoundsToRegistry("entity.twittollager.angry");
        ENTITY_TWITTOLLAGER_CHARGE = addSoundsToRegistry("entity.twittollager.charge");
        ENTITY_SPIRITCALLER_WINGS = addSoundsToRegistry("entity.spiritcaller.wings");
        ENTITY_SPIRITCALLER_AMBIENT = addSoundsToRegistry("entity.spiritcaller.ambient");
        ENTITY_SPIRITCALLER_CELEBRATE = addSoundsToRegistry("entity.spiritcaller.celebrate");
        ENTITY_SPIRITCALLER_HURT = addSoundsToRegistry("entity.spiritcaller.hurt");
        ENTITY_SPIRITCALLER_DEATH = addSoundsToRegistry("entity.spiritcaller.death");
        ENTITY_SPIRITCALLER_INTRO = addSoundsToRegistry("entity.spiritcaller.intro");
        ENTITY_SPIRITCALLER_MUSIC = addSoundsToRegistry("entity.spiritcaller.music");
        ENTITY_SPIRITCALLER_MUSIC_APRIL = addSoundsToRegistry("entity.spiritcaller.music_april");
        ENTITY_SPIRITCALLER_STEALSPIRITS = addSoundsToRegistry("entity.spiritcaller.steal_spirits");
        ENTITY_SPIRITCALLER_SPIRITABSORB = addSoundsToRegistry("entity.spiritcaller.spirit_absorb");
        ENTITY_SPIRITCALLER_SPIRITSWARM = addSoundsToRegistry("entity.spiritcaller.spirit_swarm");
        ENTITY_SPIRITCALLER_SOULSCREAM = addSoundsToRegistry("entity.spiritcaller.soul_scream");
        ENTITY_SPIRITCALLER_BLOCKALERT = addSoundsToRegistry("entity.spiritcaller.block_alert");
        ENTITY_SPIRITCALLER_EARTHRUMBLE = addSoundsToRegistry("entity.spiritcaller.earth_rumble");
        ENTITY_SPIRITCALLER_IMPLAUGH = addSoundsToRegistry("entity.spiritcaller.imp_laugh");
        ENTITY_SPIRITCALLER_DEATHANIMATION = addSoundsToRegistry("entity.spiritcaller.death_animation");
        ENTITY_SPIRITCALLER_DESCENT = addSoundsToRegistry("entity.spiritcaller.descent");
        ENTITY_SPIRITCALLER_IMPRISE = addSoundsToRegistry("entity.spiritcaller.imprise");
        ENTITY_SPIRITCALLER_CLAP = addSoundsToRegistry("entity.spiritcaller.clap");
        ENTITY_SPIRITCALLER_SPIRITHANDS = addSoundsToRegistry("entity.spiritcaller.spirit_hands");
        ENTITY_SPIRITCALLER_SPIRITHAND_WARN = addSoundsToRegistry("entity.spiritcaller.spirithand_warn");
        ENTITY_SPIRITCALLER_CHARGELASER = addSoundsToRegistry("entity.spiritcaller.charge_laser");
        ENTITY_SPIRITCALLER_LASER = addSoundsToRegistry("entity.spiritcaller.laser");
        ENTITY_SPIRITCALLER_ANTICHEESE = addSoundsToRegistry("entity.spiritcaller.anticheese");
        ENTITY_MOBSPIRIT_HURT = addSoundsToRegistry("entity.mob_spirit.hurt");
        ENTITY_MOBSPIRIT_DEATH = addSoundsToRegistry("entity.mob_spirit.death");
        ENTITY_MOBSPIRIT_HURTCORRUPTED = addSoundsToRegistry("entity.mob_spirit.hurt_corrupted");
        ENTITY_MOBSPIRIT_DEATHCORRUPTED = addSoundsToRegistry("entity.mob_spirit.death_corrupted");
        ENTITY_BOSSRANDOMIZER_AMBIENT = addSoundsToRegistry("entity.boss_randomizer.ambient");
        ENTITY_BOSSRANDOMIZER_HURT = addSoundsToRegistry("entity.boss_randomizer.hurt");
        ENTITY_BOSSRANDOMIZER_DEATH = addSoundsToRegistry("entity.boss_randomizer.death");
        ENTITY_BOSSRANDOMIZER_BOSS = addSoundsToRegistry("entity.boss_randomizer.boss");
        ENTITY_BOSSRANDOMIZER_FINALBOSS = addSoundsToRegistry("entity.boss_randomizer.finalboss");
        ENTITY_BOSSRANDOMIZER_GOOFY = addSoundsToRegistry("entity.boss_randomizer.goofy");
        ENTITY_CROCOFANG_AMBIENT = addSoundsToRegistry("entity.crocofang.ambient");
        ENTITY_CROCOFANG_BITE = addSoundsToRegistry("entity.crocofang.bite");
        ENTITY_CROCOFANG_HURT = addSoundsToRegistry("entity.crocofang.hurt");
        ENTITY_CROCOFANG_DEATH = addSoundsToRegistry("entity.crocofang.death");
        ENTITY_CROCOFANG_PREPARE_CHARGE = addSoundsToRegistry("entity.crocofang.prepare_charge");
        ENTITY_CROCOFANG_CHARGE = addSoundsToRegistry("entity.crocofang.charge");
        ENTITY_DEVASTATOR_RAVAGERMUTATE = addSoundsToRegistry("entity.devastator.ravager_mutate");
        ENTITY_DEVASTATOR_INTROEXPLOSION = addSoundsToRegistry("entity.devastator.intro_explosion");
        ENTITY_DEVASTATOR_SLAMGROUNDINTRO = addSoundsToRegistry("entity.devastator.slam_ground_intro");
        ENTITY_DEVASTATOR_INTROROAR = addSoundsToRegistry("entity.devastator.intro_roar");
        ENTITY_DEVASTATOR_DEATH = addSoundsToRegistry("entity.devastator.death");
        ENTITY_DEVASTATOR_DEATHGROUND = addSoundsToRegistry("entity.devastator.death_ground");
        ENTITY_DEVASTATOR_PREPARE_WALLCRASH = addSoundsToRegistry("entity.devastator.prepare_wallcrash");
        ENTITY_DEVASTATOR_WALLCRASH = addSoundsToRegistry("entity.devastator.wallcrash");
        ENTITY_DEVASTATOR_STEP = addSoundsToRegistry("entity.devastator.step");
        ENTITY_DEVASTATOR_LAND = addSoundsToRegistry("entity.devastator.land");
        ENTITY_ABSORBER_AMBIENT = addSoundsToRegistry("entity.absorber.ambient");
        ENTITY_ABSORBER_HURT = addSoundsToRegistry("entity.absorber.hurt");
        ENTITY_ABSORBER_DEATH = addSoundsToRegistry("entity.absorber.death");
        ENTITY_ABSORBER_ATTACK = addSoundsToRegistry("entity.absorber.attack");
        ENTITY_ABSORBER_COLLAPSE = addSoundsToRegistry("entity.absorber.collapse");
        ENTITY_PRESERVER_AMBIENT = addSoundsToRegistry("entity.preserver.ambient");
        ENTITY_PRESERVER_HURT = addSoundsToRegistry("entity.preserver.hurt");
        ENTITY_PRESERVER_DEATH = addSoundsToRegistry("entity.preserver.death");
        ENTITY_PRESERVER_JUMP = addSoundsToRegistry("entity.preserver.jump");
        ENTITY_PRESERVER_LAND = addSoundsToRegistry("entity.preserver.land");
        ENTITY_FREAKAGER_AMBIENT = addSoundsToRegistry("entity.freakager.ambient");
        ENTITY_FREAKAGER_HURT = addSoundsToRegistry("entity.freakager.hurt");
        ENTITY_FREAKAGER_DEATH = addSoundsToRegistry("entity.freakager.death");
        ENTITY_FREAKAGER_REVEAL = addSoundsToRegistry("entity.freakager.reveal");
        ENTITY_FREAKAGER_SKID = addSoundsToRegistry("entity.freakager.skid");
        ENTITY_FREAKAGER_VILLAGERWAVE = addSoundsToRegistry("entity.freakager.villager_wave");
        ENTITY_FREAKAGER_VILLAGERSIGH = addSoundsToRegistry("entity.freakager.villager_sigh");
        ENTITY_FREAKAGER_FORCEPOTION = addSoundsToRegistry("entity.freakager.force_potion");
        ENTITY_FREAKAGER_AXE_DRAW = addSoundsToRegistry("entity.freakager.axe_draw");
        ENTITY_FREAKAGER_THROW = addSoundsToRegistry("entity.freakager.throw");
        ENTITY_FREAKAGER_PUMPKINBOMBS = addSoundsToRegistry("entity.freakager.pumpkinbombs");
        ENTITY_FREAKAGER_MINIONS = addSoundsToRegistry("entity.freakager.minions");
        ENTITY_FREAKAGER_ANGRYAXES = addSoundsToRegistry("entity.freakager.angry_axes");
        ENTITY_FREAKAGER_LAUGH = addSoundsToRegistry("entity.freakager.laugh");
        ENTITY_FREAKAGER_MUSIC = addSoundsToRegistry("entity.freakager.music");
        ENTITY_FREAKAGER_VILLAGERPANIC = addSoundsToRegistry("entity.freakager.villager_panic");
        ENTITY_FREAKAGER_SHIVER = addSoundsToRegistry("entity.freakager.shiver");
        ENTITY_FREAKAGER_CYMBAL = addSoundsToRegistry("entity.freakager.cymbal");
        ENTITY_FREAKAGER_SKULLBOMB_EXPLODE = addSoundsToRegistry("entity.freakager.skullbomb_explode");
        ENTITY_FREAKAGER_PUMPKINBOMB_EXPLODE = addSoundsToRegistry("entity.freakager.pumpkinbomb_explode");
        ENTITY_FREAKAGER_VILLAGERHISS = addSoundsToRegistry("entity.freakager.villager_hiss");
        ENTITY_FREAKAGER_PUMPKINBOMB_BOING = addSoundsToRegistry("entity.freakager.pumpkinbomb_boing");
        ENTITY_FREAKAGER_SPIN = addSoundsToRegistry("entity.freakager.spin");
        ENTITY_FREAKAGER_SCYTHE_SPIN = addSoundsToRegistry("entity.freakager.scythe_spin");
        ENTITY_FREAKAGER_SCYTHE_CATCH = addSoundsToRegistry("entity.freakager.scythe_catch");
        ENTITY_FREAKAGER_TRICKORTREAT_DESTROY = addSoundsToRegistry("entity.freakager.trickortreat_destroy");
        ENTITY_FREAKAGER_TRICKORTREAT = addSoundsToRegistry("entity.freakager.trickortreat");
        ENTITY_FREAKAGER_TRICKORTREAT_BOUNCE = addSoundsToRegistry("entity.freakager.trickortreat_bounce");
        ENTITY_FREAKAGER_FUNNYBONE_AMBIENT = addSoundsToRegistry("entity.freakager.funnybone_ambient");
        ENTITY_FREAKAGER_FUNNYBONE_HURT = addSoundsToRegistry("entity.freakager.funnybone_hurt");
        ENTITY_FREAKAGER_FUNNYBONE_DEATH = addSoundsToRegistry("entity.freakager.funnybone_death");
        ENTITY_FREAKAGER_FUNNYBONE_THROW = addSoundsToRegistry("entity.freakager.funnybone_throw");
        ENTITY_FREAKAGER_EYESORE_AMBIENT = addSoundsToRegistry("entity.freakager.eyesore_ambient");
        ENTITY_FREAKAGER_EYESORE_HURT = addSoundsToRegistry("entity.freakager.eyesore_hurt");
        ENTITY_FREAKAGER_EYESORE_DEATH = addSoundsToRegistry("entity.freakager.eyesore_death");
        ENTITY_FREAKAGER_EYESORE_LAND = addSoundsToRegistry("entity.freakager.eyesore_land");
        ENTITY_RAGNO_TRANS = addSoundsToRegistry("entity.ragno.trans");
        ENTITY_RAGNO_MUSIC = addSoundsToRegistry("entity.ragno.music");
        ENTITY_RAGNO_AMBIENT = addSoundsToRegistry("entity.ragno.ambient");
        ENTITY_RAGNO_HURT = addSoundsToRegistry("entity.ragno.hurt");
        ENTITY_RAGNO_DEATH = addSoundsToRegistry("entity.ragno.death");
        ENTITY_RAGNO_CRAWL = addSoundsToRegistry("entity.ragno.crawl");
        ENTITY_RAGNO_BLOCK = addSoundsToRegistry("entity.ragno.block");
        ENTITY_RAGNO_PREPARECHARGE = addSoundsToRegistry("entity.ragno.prepare_charge");
        ENTITY_RAGNO_LEAP = addSoundsToRegistry("entity.ragno.leap");
        ENTITY_RAGNO_ROAR = addSoundsToRegistry("entity.ragno.roar");
        ENTITY_RAGNO_WEB = addSoundsToRegistry("entity.ragno.web");
        ENTITY_RAGNO_SPAWN = addSoundsToRegistry("entity.ragno.spawn");
        ENTITY_RAGNO_SCREECH = addSoundsToRegistry("entity.ragno.screech");
        ENTITY_RAGNO_JUMPSCARE = addSoundsToRegistry("entity.ragno.jumpscare");
        ENTITY_RAGNO_EAT = addSoundsToRegistry("entity.ragno.eat");
        ENTITY_RAGNO_SLAM = addSoundsToRegistry("entity.ragno.slam");
        ENTITY_RAGNO_WEB_HIT = addSoundsToRegistry("entity.ragno.web_hit");
        ENTITY_RAGNO_CHARGE = addSoundsToRegistry("entity.ragno.charge");
        ENTITY_RAGNO_COUGH = addSoundsToRegistry("entity.ragno.cough");
        ENTITY_RAGNO_STUN = addSoundsToRegistry("entity.ragno.stun");
        TOTEM_BANISHMENT = addSoundsToRegistry("item.totem_of_banishment.banish");
        SPELLBOUND_BOOK_USE = addSoundsToRegistry("item.spellbound_book.use");
        MAGI_DISC = addSoundsToRegistry("item.magi_disc.music");
        SPIRI_DISC = addSoundsToRegistry("item.spiri_disc.music");
        FREAKY_DISC = addSoundsToRegistry("item.freaky_disc.music");
        GHOST_BLOCK_REPAIR = addSoundsToRegistry("block.ghost_block.repair");
    }
}
