package com.yellowbrossproductions.illageandspillage.init;

import com.yellowbrossproductions.illageandspillage.entities.*;
import com.yellowbrossproductions.illageandspillage.entities.projectile.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EntityType.Builder;
import net.minecraft.world.entity.MobCategory;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModEntityTypes {
    public static DeferredRegister<EntityType<?>> ENTITY_TYPES;
    public static final RegistryObject<EntityType<IgniterEntity>> Igniter;
    public static final RegistryObject<EntityType<EngineerEntity>> Engineer;
    public static final RegistryObject<EntityType<ChagrinSentryEntity>> ChagrinSentry;
    public static final RegistryObject<EntityType<HinderEntity>> Hinder;
    public static final RegistryObject<EntityType<FactoryEntity>> Factory;
    public static final RegistryObject<EntityType<BeeperEntity>> Beeper;
    public static final RegistryObject<EntityType<SniperEntity>> Sniper;
    public static final RegistryObject<EntityType<PokerEntity>> Poker;
    public static final RegistryObject<EntityType<MagispellerEntity>> Magispeller;
    public static final RegistryObject<EntityType<FakeMagispellerEntity>> Faker;
    public static final RegistryObject<EntityType<DispenserEntity>> Dispenser;
    public static final RegistryObject<EntityType<IllashooterEntity>> Illashooter;
    public static final RegistryObject<EntityType<CrashagerEntity>> Crashager;
    public static final RegistryObject<EntityType<BossRandomizerEntity>> BossRandomizer;
    public static final RegistryObject<EntityType<TwittollagerEntity>> Twittollager;
    public static final RegistryObject<EntityType<SpiritcallerEntity>> Spiritcaller;
    public static final RegistryObject<EntityType<MobSpiritEntity>> MobSpirit;
    public static final RegistryObject<EntityType<IllagerSoulEntity>> IllagerSoul;
    public static final RegistryObject<EntityType<ImpEntity>> Imp;
    public static final RegistryObject<EntityType<SpiritHandEntity>> SpiritHand;
    public static final RegistryObject<EntityType<SoulBeamEntity>> SoulBeam;
    public static final RegistryObject<EntityType<IgniterFireballEntity>> IgniterFireball;
    public static final RegistryObject<EntityType<CrocofangEntity>> Crocofang;
    public static final RegistryObject<EntityType<CameraShakeEntity>> CameraShake;
    //    public static final RegistryObject<EntityType<DevastatorEntity>> Devastator;
    public static final RegistryObject<EntityType<AbsorberEntity>> Absorber;
    public static final RegistryObject<EntityType<PreserverEntity>> Preserver;
    public static final RegistryObject<EntityType<HayArmorEntity>> HayArmor;
    public static final RegistryObject<EntityType<FreakagerEntity>> Freakager;
    public static final RegistryObject<EntityType<RagnoEntity>> Ragno;
    public static final RegistryObject<EntityType<EyesoreEntity>> Eyesore;
    public static final RegistryObject<EntityType<FunnyboneEntity>> Funnybone;
    public static final RegistryObject<EntityType<BoneEntity>> Bone;
    public static final RegistryObject<EntityType<SkullBombEntity>> SkullBomb;
    public static final RegistryObject<EntityType<OldMagispellerEntity>> OldMagispeller;
    public static final RegistryObject<EntityType<MagiFireballEntity>> MagiFireball;
    public static final RegistryObject<EntityType<MagiArrowEntity>> MagiArrow;
    public static final RegistryObject<EntityType<MagiHealEntity>> MagiHeal;
    public static final RegistryObject<EntityType<KaboomerEntity>> Kaboomer;
    public static final RegistryObject<EntityType<PumpkinBombEntity>> PumpkinBomb;
    public static final RegistryObject<EntityType<AxeEntity>> Axe;
    public static final RegistryObject<EntityType<DarkPotionEntity>> DarkPotion;
    public static final RegistryObject<EntityType<ScytheEntity>> Scythe;
    public static final RegistryObject<EntityType<TrickOrTreatEntity>> TrickOrTreat;
    public static final RegistryObject<EntityType<WebEntity>> Web;
    public static final RegistryObject<EntityType<WebNetEntity>> WebNet;
    public static final RegistryObject<EntityType<VillagerSoulEntity>> VillagerSoul;

    public static void onAttribute(EntityAttributeCreationEvent event) {
        event.put(Igniter.get(), IgniterEntity.createAttributes().build());
        event.put(Engineer.get(), EngineerEntity.createAttributes().build());
        event.put(ChagrinSentry.get(), ChagrinSentryEntity.createAttributes().build());
        event.put(Hinder.get(), HinderEntity.createAttributes().build());
        event.put(Factory.get(), FactoryEntity.createAttributes().build());
        event.put(Beeper.get(), BeeperEntity.createAttributes().build());
        event.put(Sniper.get(), SniperEntity.createAttributes().build());
        event.put(Poker.get(), PokerEntity.createAttributes().build());
        event.put(Magispeller.get(), MagispellerEntity.createAttributes().build());
        event.put(Faker.get(), FakeMagispellerEntity.createAttributes().build());
        event.put(Dispenser.get(), DispenserEntity.createAttributes().build());
        event.put(Illashooter.get(), IllashooterEntity.createAttributes().build());
        event.put(Crashager.get(), CrashagerEntity.createAttributes().build());
        event.put(BossRandomizer.get(), BossRandomizerEntity.createAttributes().build());
        event.put(Twittollager.get(), TwittollagerEntity.createAttributes().build());
        event.put(Spiritcaller.get(), SpiritcallerEntity.createAttributes().build());
        event.put(MobSpirit.get(), MobSpiritEntity.createAttributes().build());
        event.put(IllagerSoul.get(), IllagerSoulEntity.createAttributes().build());
        event.put(Imp.get(), ImpEntity.createAttributes().build());
        event.put(SpiritHand.get(), SpiritHandEntity.createAttributes().build());
        event.put(Crocofang.get(), CrocofangEntity.createAttributes().build());
//        event.put(Devastator.get(), DevastatorEntity.createAttributes().build());
        event.put(Absorber.get(), AbsorberEntity.createAttributes().build());
        event.put(Preserver.get(), PreserverEntity.createAttributes().build());
        event.put(HayArmor.get(), HayArmorEntity.createAttributes().build());
        event.put(Freakager.get(), FreakagerEntity.createAttributes().build());
        event.put(Ragno.get(), RagnoEntity.createAttributes().build());
        event.put(Eyesore.get(), EyesoreEntity.createAttributes().build());
        event.put(Funnybone.get(), FunnyboneEntity.createAttributes().build());
        event.put(SkullBomb.get(), SkullBombEntity.createAttributes().build());
        event.put(OldMagispeller.get(), OldMagispellerEntity.createAttributes().build());
        event.put(MagiHeal.get(), MagiHealEntity.createAttributes().build());
        event.put(Kaboomer.get(), KaboomerEntity.createAttributes().build());
        event.put(PumpkinBomb.get(), PumpkinBombEntity.createAttributes().build());
        event.put(Scythe.get(), ScytheEntity.createAttributes().build());
        event.put(TrickOrTreat.get(), TrickOrTreatEntity.createAttributes().build());
        event.put(Web.get(), WebEntity.createAttributes().build());
        event.put(WebNet.get(), WebNetEntity.createAttributes().build());
        event.put(VillagerSoul.get(), VillagerSoulEntity.createAttributes().build());
    }

    static {
        ENTITY_TYPES = DeferredRegister.create(ForgeRegistries.ENTITY_TYPES, "illageandspillage");
        Igniter = ENTITY_TYPES.register("igniter", () -> Builder.of(IgniterEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "igniter")).toString()));
        Engineer = ENTITY_TYPES.register("engineer", () -> Builder.of(EngineerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "engineer")).toString()));
        ChagrinSentry = ENTITY_TYPES.register("chagrin_sentry", () -> Builder.of(ChagrinSentryEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "chagrin_sentry")).toString()));
        Hinder = ENTITY_TYPES.register("hinder", () -> Builder.of(HinderEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "hinder")).toString()));
        Factory = ENTITY_TYPES.register("factory", () -> Builder.of(FactoryEntity::new, MobCategory.MONSTER).sized(1.2F, 0.95F).build((new ResourceLocation("illageandspillage", "factory")).toString()));
        Beeper = ENTITY_TYPES.register("beeper", () -> Builder.of(BeeperEntity::new, MobCategory.MONSTER).sized(0.4F, 0.95F).build((new ResourceLocation("illageandspillage", "beeper")).toString()));
        Sniper = ENTITY_TYPES.register("sniper", () -> Builder.of(SniperEntity::new, MobCategory.MONSTER).sized(0.5F, 0.95F).build((new ResourceLocation("illageandspillage", "sniper")).toString()));
        Poker = ENTITY_TYPES.register("poker", () -> Builder.of(PokerEntity::new, MobCategory.MONSTER).sized(0.5F, 0.95F).build((new ResourceLocation("illageandspillage", "poker")).toString()));
        Magispeller = ENTITY_TYPES.register("magispeller", () -> Builder.of(MagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build((new ResourceLocation("illageandspillage", "magispeller")).toString()));
        Faker = ENTITY_TYPES.register("faker", () -> Builder.of(FakeMagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build((new ResourceLocation("illageandspillage", "faker")).toString()));
        Dispenser = ENTITY_TYPES.register("dispenser", () -> Builder.of(DispenserEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).build((new ResourceLocation("illageandspillage", "dispenser")).toString()));
        Illashooter = ENTITY_TYPES.register("illashooter", () -> Builder.of(IllashooterEntity::new, MobCategory.MONSTER).sized(0.5F, 1.0F).build((new ResourceLocation("illageandspillage", "illashooter")).toString()));
        Crashager = ENTITY_TYPES.register("crashager", () -> Builder.of(CrashagerEntity::new, MobCategory.MONSTER).sized(1.95F, 2.2F).fireImmune().build((new ResourceLocation("illageandspillage", "crashager")).toString()));
        BossRandomizer = ENTITY_TYPES.register("boss_randomizer", () -> Builder.of(BossRandomizerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "boss_randomizer")).toString()));
        Twittollager = ENTITY_TYPES.register("twittollager", () -> Builder.of(TwittollagerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "twittollager")).toString()));
        Spiritcaller = ENTITY_TYPES.register("spiritcaller", () -> Builder.of(SpiritcallerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.4F).build((new ResourceLocation("illageandspillage", "spiritcaller")).toString()));
        MobSpirit = ENTITY_TYPES.register("mob_spirit", () -> Builder.of(MobSpiritEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build((new ResourceLocation("illageandspillage", "mob_spirit")).toString()));
        IllagerSoul = ENTITY_TYPES.register("illager_soul", () -> Builder.of(IllagerSoulEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build((new ResourceLocation("illageandspillage", "illager_soul")).toString()));
        IgniterFireball = ENTITY_TYPES.register("igniter_fireball", () -> Builder.<IgniterFireballEntity>of(IgniterFireballEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build((new ResourceLocation("illageandspillage", "igniter_fireball")).toString()));
        Imp = ENTITY_TYPES.register("imp", () -> Builder.of(ImpEntity::new, MobCategory.CREATURE).sized(1.0F, 3.0F).fireImmune().build((new ResourceLocation("illageandspillage", "imp")).toString()));
        SpiritHand = ENTITY_TYPES.register("spirit_hand", () -> Builder.of(SpiritHandEntity::new, MobCategory.CREATURE).sized(1.5F, 1.5F).fireImmune().build((new ResourceLocation("illageandspillage", "spirit_hand")).toString()));
        SoulBeam = ENTITY_TYPES.register("soul_beam", () -> Builder.<SoulBeamEntity>of(SoulBeamEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build((new ResourceLocation("illageandspillage", "soul_beam")).toString()));
        Crocofang = ENTITY_TYPES.register("crocofang", () -> Builder.of(CrocofangEntity::new, MobCategory.MONSTER).sized(2.0F, 1.4F).build((new ResourceLocation("illageandspillage", "crocofang")).toString()));
        CameraShake = ENTITY_TYPES.register("camera_shake", () -> Builder.<CameraShakeEntity>of(CameraShakeEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build((new ResourceLocation("illageandspillage", "camera_shake")).toString()));
//        Devastator = ENTITY_TYPES.register("devastator", () -> {
//            return Builder.of(DevastatorEntity::new, MobCategory.MONSTER).sized(5.4F, 8.75F).build((new ResourceLocation("illageandspillage", "devastator")).toString());
//        });
        Absorber = ENTITY_TYPES.register("absorber", () -> Builder.of(AbsorberEntity::new, MobCategory.MONSTER).sized(1.3F, 2.9F).build((new ResourceLocation("illageandspillage", "absorber")).toString()));
        Preserver = ENTITY_TYPES.register("preserver", () -> Builder.of(PreserverEntity::new, MobCategory.MONSTER).sized(1.1F, 1.95F).build((new ResourceLocation("illageandspillage", "preserver")).toString()));
        HayArmor = ENTITY_TYPES.register("hay_armor", () -> Builder.of(HayArmorEntity::new, MobCategory.MISC).sized(1.0F, 1.0F).build((new ResourceLocation("illageandspillage", "hay_armor")).toString()));
        Freakager = ENTITY_TYPES.register("freakager", () -> Builder.of(FreakagerEntity::new, MobCategory.MONSTER).sized(0.6F, 1.95F).build((new ResourceLocation("illageandspillage", "freakager")).toString()));
        Ragno = ENTITY_TYPES.register("ragno", () -> Builder.of(RagnoEntity::new, MobCategory.MONSTER).sized(3.2F, 1.8F).build((new ResourceLocation("illageandspillage", "ragno")).toString()));
        Eyesore = ENTITY_TYPES.register("eyesore", () -> Builder.of(EyesoreEntity::new, MobCategory.MONSTER).sized(0.8F, 0.8F).build((new ResourceLocation("illageandspillage", "eyesore")).toString()));
        Funnybone = ENTITY_TYPES.register("funnybone", () -> Builder.of(FunnyboneEntity::new, MobCategory.MONSTER).sized(0.5F, 1.2F).build((new ResourceLocation("illageandspillage", "funnybone")).toString()));
        Bone = ENTITY_TYPES.register("bone", () -> Builder.<BoneEntity>of(BoneEntity::new, MobCategory.MONSTER).sized(0.5F, 0.1F).build((new ResourceLocation("illageandspillage", "bone")).toString()));
        SkullBomb = ENTITY_TYPES.register("skull_bomb", () -> Builder.of(SkullBombEntity::new, MobCategory.MONSTER).sized(0.5F, 0.5F).build((new ResourceLocation("illageandspillage", "skull_bomb")).toString()));
        OldMagispeller = ENTITY_TYPES.register("old_magispeller", () -> Builder.of(OldMagispellerEntity::new, MobCategory.MONSTER).sized(0.6F, 2.3F).build((new ResourceLocation("illageandspillage", "old_magispeller")).toString()));
        MagiFireball = ENTITY_TYPES.register("magi_fireball", () -> Builder.<MagiFireballEntity>of(MagiFireballEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build((new ResourceLocation("illageandspillage", "magi_fireball")).toString()));
        MagiArrow = ENTITY_TYPES.register("magi_arrow", () -> Builder.<MagiArrowEntity>of(MagiArrowEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build((new ResourceLocation("illageandspillage", "magi_arrow")).toString()));
        MagiHeal = ENTITY_TYPES.register("magi_heal", () -> Builder.of(MagiHealEntity::new, MobCategory.MONSTER).sized(0.5F, 0.5F).build((new ResourceLocation("illageandspillage", "magi_heal")).toString()));
        Kaboomer = ENTITY_TYPES.register("kaboomer", () -> Builder.of(KaboomerEntity::new, MobCategory.MONSTER).sized(1.25F, 3.4F).fireImmune().build((new ResourceLocation("illageandspillage", "kaboomer")).toString()));
        PumpkinBomb = ENTITY_TYPES.register("pumpkin_bomb", () -> Builder.of(PumpkinBombEntity::new, MobCategory.MONSTER).sized(0.75F, 0.75F).build((new ResourceLocation("illageandspillage", "pumpkin_bomb")).toString()));
        Axe = ENTITY_TYPES.register("axe", () -> Builder.<AxeEntity>of(AxeEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build((new ResourceLocation("illageandspillage", "axe")).toString()));
        DarkPotion = ENTITY_TYPES.register("dark_potion", () -> Builder.of(DarkPotionEntity::new, MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(1).build((new ResourceLocation("illageandspillage", "dark_potion")).toString()));
        Scythe = ENTITY_TYPES.register("scythe", () -> Builder.of(ScytheEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build((new ResourceLocation("illageandspillage", "scythe")).toString()));
        TrickOrTreat = ENTITY_TYPES.register("trick_or_treat", () -> Builder.of(TrickOrTreatEntity::new, MobCategory.MONSTER).sized(1.0F, 1.8F).build((new ResourceLocation("illageandspillage", "trick_or_treat")).toString()));
        Web = ENTITY_TYPES.register("web", () -> Builder.of(WebEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build((new ResourceLocation("illageandspillage", "web")).toString()));
        WebNet = ENTITY_TYPES.register("web_net", () -> Builder.of(WebNetEntity::new, MobCategory.MONSTER).sized(0.2F, 0.2F).build((new ResourceLocation("illageandspillage", "web_net")).toString()));
        VillagerSoul = ENTITY_TYPES.register("villager_soul", () -> Builder.of(VillagerSoulEntity::new, MobCategory.MONSTER).sized(1.0F, 1.0F).fireImmune().build((new ResourceLocation("illageandspillage", "villager_soul")).toString()));
    }
}
